title: Joey Rosicka
description: Portfolio and Blog
author: Joey Rosicka
logo: /static/img/profilePicture.jpg
github: https://github.com/JRosicka
about: Software Engineer | Game Developer

baseurl: ""
url: "//joeyrosicka.com"

allowsearch: false
allowsocials: false

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 5
per_page: 5
paginate_path: "/blog/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
