title: Joey Rosicka
description: My Personal Blog
author: Joey Rosicka
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/codeasashu
about: Software Engineer | Game Developer

baseurl: ""
url: "//joeyrosicka.com"

# Enables the search bar at the top of the page. I haven't really looked at how well it works. 
allowsearch: false

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
