title: Joey Rosicka
description: My Personal Blog
author: Joey Rosicka
logo: /static/img/avatar.png
github: https://github.com/JRosicka
about: Software Engineer | Game Developer

baseurl: ""
url: "//joeyrosicka.com"

allowsearch: false

disqus_shortname: aboutjoey

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
